<?php

/**
 * Model_Base_PerformanceIndicator
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $program_id
 * @property Model_Program $Program
 * @property Doctrine_Collection $EvaluationForms
 * @property Doctrine_Collection $EvaluationFormXPerformanceIndicator
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_PerformanceIndicator extends Core_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('performance_indicator');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('program_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_Program as Program', array(
             'local' => 'program_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('Model_EvaluationForm as EvaluationForms', array(
             'refClass' => 'Model_EvaluationFormXPerformanceIndicator',
             'local' => 'performance_indicator_id',
             'foreign' => 'evaluation_form_id'));

        $this->hasMany('Model_EvaluationFormXPerformanceIndicator as EvaluationFormXPerformanceIndicator', array(
             'local' => 'id',
             'foreign' => 'performance_indicator_id'));
    }
}