<?php

/**
 * Model_PerformanceIndicatorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_PerformanceIndicatorTable extends Core_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_PerformanceIndicatorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_PerformanceIndicator');
    }

    /**
     * Return true if entity with specified program ID and name exists
     *
     * @param $programId
     * @param $name
     * @return bool
     */
    public function isExists($programId, $name)
    {
        return ($this->createQuery('pI')
            ->andWhere('program_id = ?', $programId)
            ->andWhere('name = ?', $name)
            ->count());
    }
}