<?php

/**
 * Model_ProgramTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_ProgramTable extends Core_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return Model_ProgramTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Program');
    }
}
